--Script hau sartu sql develop-en eta exekutatu
--Saltzaileak
UPDATE LANGILE SET SOLDATA = 30000 WHERE ID= ANY (SELECT L.ID FROM LANGILE L INNER JOIN SALTZAILE S ON L.ID = S.ID);
 
--Bulegariak
UPDATE LANGILE SET SOLDATA = 30000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '1' );
UPDATE LANGILE SET SOLDATA = 31000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '2' );
UPDATE LANGILE SET SOLDATA = 32000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '3' );
UPDATE LANGILE SET SOLDATA = 33000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '4' );
UPDATE LANGILE SET SOLDATA = 34000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '5' );
UPDATE LANGILE SET SOLDATA = 35000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '6' );
UPDATE LANGILE SET SOLDATA = 36000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '7' );
UPDATE LANGILE SET SOLDATA = 37000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '8' );
UPDATE LANGILE SET SOLDATA = 38000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '9' );
UPDATE LANGILE SET SOLDATA = 39000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '10' );
UPDATE LANGILE SET SOLDATA = 40000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '11' );
UPDATE LANGILE SET SOLDATA = 41000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '12' );
UPDATE LANGILE SET SOLDATA = 42000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '13' );
UPDATE LANGILE SET SOLDATA = 43000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '14' );
UPDATE LANGILE SET SOLDATA = 44000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '15' );
UPDATE LANGILE SET SOLDATA = 45000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '16' );
UPDATE LANGILE SET SOLDATA = 46000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '17' );
UPDATE LANGILE SET SOLDATA = 47000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '18' );
UPDATE LANGILE SET SOLDATA = 48000 WHERE ID = (SELECT ID FROM BULEGARI  WHERE LANPOSTU_ID = '19' );
